### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [choener/BiobaseBlast#10]
```
BiobaseBlast                   > Building library for BiobaseBlast-0.3.3.0..
BiobaseBlast                   > [1 of 9] Compiling Biobase.BLAST.Types
BiobaseBlast                   > 
BiobaseBlast                   > /tmp/stack-0b306fde449f19cc/BiobaseBlast-0.3.3.0/Biobase/BLAST/Types.hs:34:33: error:
BiobaseBlast                   >     • Couldn't match type: HM.HashMap T.Text v0
BiobaseBlast                   >                      with: Data.Aeson.KeyMap.KeyMap Value
BiobaseBlast                   >       Expected: HM.HashMap T.Text v0 -> Object
BiobaseBlast                   >         Actual: HM.HashMap T.Text v0 -> HM.HashMap T.Text v0
BiobaseBlast                   >     • In the second argument of ‘(.)’, namely
BiobaseBlast                   >         ‘HM.fromList . map lowerPair . HM.toList’
BiobaseBlast                   >       In the first argument of ‘($)’, namely
BiobaseBlast                   >         ‘Object . HM.fromList . map lowerPair . HM.toList’
BiobaseBlast                   >       In the expression:
BiobaseBlast                   >         Object . HM.fromList . map lowerPair . HM.toList $ o
BiobaseBlast                   >    |
BiobaseBlast                   > 34 | jsonLower (Object o) = Object . HM.fromList . map lowerPair . HM.toList $ o
BiobaseBlast                   >    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BiobaseBlast                   > 
BiobaseBlast                   > /tmp/stack-0b306fde449f19cc/BiobaseBlast-0.3.3.0/Biobase/BLAST/Types.hs:34:75: error:
BiobaseBlast                   >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
BiobaseBlast                   >                      with: HM.HashMap T.Text v0
BiobaseBlast                   >       Expected: HM.HashMap T.Text v0
BiobaseBlast                   >         Actual: Object
BiobaseBlast                   >     • In the second argument of ‘($)’, namely ‘o’
BiobaseBlast                   >       In the expression:
BiobaseBlast                   >         Object . HM.fromList . map lowerPair . HM.toList $ o
BiobaseBlast                   >       In an equation for ‘jsonLower’:
BiobaseBlast                   >           jsonLower (Object o)
BiobaseBlast                   >             = Object . HM.fromList . map lowerPair . HM.toList $ o
BiobaseBlast                   >             where
BiobaseBlast                   >                 lowerPair (key, val) = (T.toLower key, val)
BiobaseBlast                   >    |
BiobaseBlast                   > 34 | jsonLower (Object o) = Object . HM.fromList . map lowerPair . HM.toList $ o
BiobaseBlast                   >    |                                                                           ^
```
